sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=wirnexteam/demo-ci-nodejs
    - DOCKER_COMPOSE_VERSION=1.8.1
    - COMPOSE_INTERACTIVE_NO_CLI=1

before_install:
  - echo Before-Install-OK

before_script:
  - echo Before-Script-OK

install:
  - docker build -t main .

script:
  - printenv
  - docker run main npm run test

